language: node_js

node_js:
  - 'stable'
script:
  - yarn test
before_script:
  - npm prune
install:
  - yarn install
after_success:
  - yarn build
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist
  on:
    branch: master
